name: food_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  flare_splash_screen: ^2.0.1+2
  flutter_statusbarcolor: ^0.2.3
  flutter_custom_clippers: ^1.1.2
  percent_indicator: ^2.0.1
  shared_preferences: ^0.5.6
  logging: ^0.11.4
  dio: ^3.0.8
  rxdart: ^0.23.1
  fluttertoast: ^3.1.3
  flutter_spinkit: ^3.1.0
  firebase_auth: ^0.18.4+1
  image_picker: ^0.6.6+5
  json_annotation: ^3.0.1
  flutter_rating_bar: ^3.0.0+1
  permission_handler: ^3.0.0
  google_sign_in: ^4.5.9
  google_maps_flutter: ^0.5.25+3
  flutter_facebook_auth: ^2.0.2
  flutter_facebook_login: ^3.0.0
  pin_entry_text_field: ^0.1.4
  google_maps_place_picker: ^0.9.1
  firebase_core: ^0.5.1
  syncfusion_flutter_sliders: ^18.3.35-beta
  geolocator: ^5.3.0
  location: ^2.5.3
  geocoder: ^0.2.1
  uuid: 2.2.2
#  paytm: ^1.0.8
  upi_india: ^2.1.2
  flutter_polyline_points: ^0.1.0
  webview_flutter: ^0.3.3
  scrollable_clean_calendar: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/ic_applogo.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: productsans_bold
      fonts:
        - asset: assets/font/productsans_bold.ttf
    - family: productsans_regular
      fonts:
        - asset: assets/font/productsans_regular.ttf
    - family: CustomIcon
      fonts:
        - asset: assets/font/CustomIcon.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
